<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher List Report</title>

    <style>

        *{
            margin:0;
            padding:0;
            box-sizing:border-box;
            font-family:Arial,sans-serif;
        }

        body{
            padding:40px;
            color:#222;
        }

        .header{
            text-align:center;
            margin-bottom:25px;
        }

        .header img{
            width:90px;
            margin-bottom:10px;
        }

        .header h2{
            margin-bottom:5px;
        }

        .header h3{
            color:#2563eb;
            margin-top:8px;
        }

        .info{
            display:flex;
            justify-content:space-between;
            margin:20px 0;
            font-size:14px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        table th{

            background:#2563eb;
            color:white;
            padding:10px;
            border:1px solid #ccc;

        }

        table td{

            border:1px solid #ccc;
            padding:10px;

        }

        table tr:nth-child(even){

            background:#f8fafc;

        }

        img{

            width:60px;
            height:60px;
            border-radius:50%;
            object-fit:cover;

        }

        .footer{

            margin-top:50px;
            display:flex;
            justify-content:space-between;

        }

        .signature{

            text-align:center;
            width:220px;

        }

        .signature p{

            margin-top:70px;
            border-top:1px solid #000;

        }

        @media print{

            @page{

                size:A4;

                margin:20mm;

            }

        }

    </style>

</head>

<body>

<div class="header">

    {{-- University Logo --}}
    {{-- <img src="{{ public_path('images/logo.png') }}"> --}}

    <h2>NORTON UNIVERSITY</h2>

    <h4>Faculty of Information Technology</h4>

    <h3>TEACHER LIST REPORT</h3>

</div>

<div class="info">

    <div>

        <strong>Total Teachers :</strong>

        {{ $teachers->count() }}

    </div>

    <div>

        <strong>Print Date :</strong>

        {{ now()->format('d M Y H:i') }}

    </div>

</div>

<table>

<thead>

<tr>

<th>No</th>

<th>Photo</th>

<th>Teacher Code</th>

<th>Teacher Name</th>

<th>Department</th>

<th>Phone</th>

<th>Email</th>

<th>Status</th>

</tr>

</thead>

<tbody>

@foreach($teachers as $teacher)

<tr>

<td>{{ $loop->iteration }}</td>

<td align="center">

@if($teacher->photo)

<img src="{{ asset('storage/'.$teacher->photo) }}">

@else

No Image

@endif

</td>

<td>{{ $teacher->teacher_code }}</td>

<td>

{{ $teacher->first_name_english }}

{{ $teacher->last_name_english }}

</td>

<td>

{{ optional($teacher->department)->department_name_english }}

</td>

<td>{{ $teacher->phone }}</td>

<td>{{ $teacher->email }}</td>

<td>{{ $teacher->status }}</td>

</tr>

@endforeach

</tbody>

</table>

<div class="footer">

<div>

Generated by University Track System

</div>

<div class="signature">

<p>

Administrator

</p>

</div>

</div>

<script>

window.onload=function(){

window.print();

}

</script>

</body>

</html>